### ISSUE TITLE
set state with template 

### ISSUE THREAD

**Issue by DTekNOdev** [domectrl/ha-slow_pwm#30]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/antonverburg/ha_slow_pwm/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

This is working well for me but it would be more useful if the state could be set in a template.

### Describe the solution you'd like

It would be a simpler configuration if I could just put the state template in the configuration.

### Describe alternatives you've considered

 Currently I am using another template and an automation to set the state when the state of my template changes. 

### Additional context

My power setting to the PWM integration is the difference between setpoint and current temperature, scaled`, in the range 10-100.

All this could be eliminated if the pwm integration could set the state from a template directly.
```
template:
  - sensor:
      - name: "Towel bathroom power"
        unique_id: 01938694-e071-70a3-a3fc-baf125d7615e
        state: >-
          {% set newstate = ((state_attr('climate.thermostat_bathroom', 'temperature') |float) 
           - (state_attr('climate.thermostat_bathroom', 'current_temperature')|float)) *90 +10 %}
          {{ max(min(newstate, 100), 10) }}
```
Automation:

```
alias: Set towel rail power
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.towel_bathroom_power
conditions: []
actions:
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ states('sensor.towel_bathroom_power')}}"
    target:
      entity_id: number.towel_rail_bathroom_pwm
mode: single
``
